### PR TITLE
trilium: add desktop item

### PR DESCRIPTION
**Pull request by emmanuelrosa**
This change adds a .desktop file so that Trilium can be launched
from desktop menu systems.

### CODE REVIEW

**Comment by dtzWill** [comment]
LGTM, thanks!

Didn't notice--for whatever reason `rofi` managed to find it anyway, but I'm not sure how :).
(it seems likely to only work after running Trilium, however it does it, without this change)

Added nit commit.

FWIW beta for 0.27 is out! :)

**Comment by dtzWill** [comment]
Since we're using this, it seems it'd be better to submit upstream? I'll put that together in a few...

**Comment by emmanuelrosa** [comment]
Yes, to my surprise `rofi` found Trilium. However in my case that menu item didn't work. I discovered a .desktop file for Trilium in `$HOME/.local/share/applications`, and I'm assuming Trilium created it.

Oh, 0.27 claims to have a responsive UI. Yes!

**Comment by emmanuelrosa** [comment]
> Since we're using this, it seems it'd be better to submit upstream? I'll put that together in a few...

Agreed. Having been using this successfully for a few weeks, I trust the package is ready to go upstream.

I've actually been using it as an overlay rather than from this branch.

**Pull request merged**
